---
title: "Class 03"
author: Jonathan Tannen
output: 
  beamer_presentation:
    theme: "metropolis"
    includes:
      in_header: "preamble.tex"
---

## Agenda

- Presentation: Fay Walker of the Urban Institute
- Discuss Presentations

---

## Looking Back

Any questions?

- GitHub Setup
- Projects overall

---

## Note: Large File Storage

https://towardsdatascience.com/uploading-large-files-to-github-dbef518fa1a


---

## Looking Ahead

Next Week:

- Better Engineering: File Organization and Modularity
- Data Presentations


**In Person!**


---

## Looking Ahead: Presentations

An exploratory descriptive analysis of your dataset(s). Include summary statistics and visualizations that speak to your research question. All relevant code and files should be in your GitHub repo.

Presentation:

- A 7 minute presentation to your peers (with 3 min questions).
- Include 
    - Your question.
    - Your data sources.
    - Descriptive statistics, plots and/or maps of your variables.
    - Open question and most important next steps.
    
Presentation, and all data and scripts should be committed to your GitHub repo by midnight, Thursday.

*No write-up necessary.*

***These can be somewhat informal.***

---

## Looking Ahead: Presentations

Peers will ask: 

- Is the question clear, answerable, and implicating?
- What risks do you see in the next steps? What should be de-risked?
- Give one thing that is well done, and one area of growth.

---

## Looking Ahead: Presentations

I will send out a survey with time sign-ups.

Need two moderators who will...

- Track time of presentations.
- Handle A/V.


---

## Looking Ahead: Class

Need speakers for March and April!

Will send out a form for you to (a) suggest people, (b) request topics.

