---
output: pdf_document
urlcolor: blue
---

# MUSA Capstone: Advanced Topics in GIS
## CPLN 680 / LARP 745

## Course Syllabus

### Details

**Instructor**: Jonathan Tannen, jonathan.tannen@gmail.com  
**When**: Fridays, 8:30am - 11:30am  
**Where**: 407 Fisher-Bennet Hall  
**Zoom (January 14 & 21)**:  
- **Link**: https://upenn.zoom.us/j/97050641472?pwd=WGRSc0M2L0RWVmNhUmhRTE55czR6Zz09  
- **Meeting ID**: 970 5064 1472  
- **Passcode**: 942565  


### Description
This course offers an opportunity to work on independent projects involving the development and/or application of geographic information systems (GIS).

The course is organized as a seminar: a series of weekly meetings and concurrent assignments that ultimately
lead to the implementation and presentation of student-initiated projects. Early in the semester, each student
selects a term project dealing with one particular topic in the field of GIS, broadly defined. Topics may range
from the basic development of geospatial tools and techniques to practical applications in any of a variety of
fields.

Class time will be a combination of structured collaboration, external speakers, and (possibly) lectures on relevant content.

### Course Resources
The course's GitHub repo will be the source of truth for the course.  
https://github.com/CPLN-680-Spring-2022/Class-Resources  

However, I've also created a Canvas page for email announcements and collection of assignments (if necessary).


### Project Description
The requirements for the final project are intentionally broad, as students are expected to develop one that suits their interests.

Possible project formats include:  

- A research paper with GIS analysis about a substantive question.
- A research paper about GIS or spatial methodology.
- Construction of a GIS tool.
- A dashboard *answering a question*. (The dashboard cannot simply be a view of the data. It must be targeted towards a novel question.)

For all projects, a complete set of data, scripts, and reports must be provided via GitHub or Google Drive. This should include the raw data, and all processing and analysis.

Students will present on their projects in the final two sessions of the class.

### Course Calendar
*This calendar is tentative. We will revisit it as we continue the semester.*

| Date | Assignment Due | Class Time |
|-|---|-----|
|Jan 14 (Virtual)| Initial Topic Brainstorm | Introduction, Syllabus, Share Topics, Turnout Tracker Presentation |
|Jan 21 (Virtual)| Project Proposal 0 | Share Project Proposal, Better Engineering: Github |
|Jan 28| GitHub Repo with initial data | Fay Walker (Urban Institute) |
|Feb 4| Data Summary Analysis | Better Engineering: File Organization, Proposal & Data Summary Presentations A |
|Feb 11| -- | Michelle Montalvo and Seth Bluestein (Philadelphia City Commissioners Office), Proposal & Data Summary Presentations B|
|Feb 18| Project Proposal 1 | Dan Lopez (Office of Innovation and Technology), Better Engineering: Code Modularity, Working Groups |
|Feb 25| -- | Nick Hand (Office of the City Controller), Working Groups |
|Mar 4| Mid-point Work In Progress | Working Groups |
|Mar 11| *Spring Break* |  |
|Mar 18| -- | Better Engineering: Code Review, Mid-point Presentations A |
|Mar 25| Feedback for 2 peer projects | Spatial Regression Models, Mid-point Presentations B |
|Apr 1| Peer Code Review | Megan Todd (Philadelphia Dept of Public Health) |
|Apr 8| -- | Brook Guzder-Williams (World Resources Institute) |
|Apr 15| Final Presentation (1) |  |
|Apr 22| Final Presentation (2) |  |
|Apr 29| *No Class*, Final Projects due | |

### Office Hours
Office hours will be by appointment. They can be in person or by video chat.

Wednesdays from 6pm - 8pm  
Location: Zoom (link will be generated at sign-up)  
Sign-up: https://calendly.com/jtannen/office-hours  

### Grading
Final Project: 50%  
Final Presentation: 25%  
Class Participation & Preparation: 25%  

### Assignments

Assignments must be submitted by the time the class meets. 
The first two assignments can be submitted on Canvas or by email. 
Subsequent assignments should be uploaded to GitHub.  

**01-14 Initial Topic Brainstorm**: One-page (or less) document summarizing 

- your topic
- an open question in the topic to research
- format of your final deliverable
- possible data sources

*These will be considered non-binding proposals. The goal is to get you to start brainstorming.*

**01-21 Project Proposal 0**: Two-page (or less) document with   

* Motivation
    * Is your project answering a question or solving a task? 
    * Is your question causal or descriptive?
    * (Brief) Summary of existing relevant research
* Datasets identified
* High-level summary of methods
* Describe deliverables
    * How will this be used? Describe a hypothetical user journey.
        * If a research paper, what will be the policy implications?

**01-28 GitHub Repo**: Share a GitHub repo for your project, with  
- Raw data in a `raw_data/` directory.  
- Any scripts, files, or cleaned data.  
- A README file in the top directory.  

**02-04 Data Summary Analysis**: An exploratory descriptive analysis of your dataset(s). Include summary statistics and visualizations that speak to your research question. All relevant code and files should be in your GitHub repo.

Presentation:

- A 7 minute presentation to your peers (with 3 min questions).
- Include 
    - Your topic and question.
    - Your data sources.
    - Descriptive statistics, plots and/or maps of your variables.
    - Open question and most important next steps.

**02-18 Project Proposal 1**: An update of Project Proposal 0, with motivating data summary. This may just be a concatenated version of your Proposal 0 and Data Analysis, but your question and deliverable may have also changed.

**03-04 Work in Progress Report**: A draft of your project, to be reviewed by two peers. Provide as much analysis as you can, to be able to get proper feedback.

Should include  

- Introduction and motivation.
- Short literature review.
- Initial analysis and/or technical implementation.

*These will be presented as Mid-Point Presentations (10 min + 5 min Q&A) on March 18.*

**03-25 Peer Feedback**: Peer review of two projects. 

Your review should be 1-2 pages, and provide helpful feedback for the author. 

**Submit these to Canvas.**

Considering the following questions may be useful:

- Is the question clearly stated and well motivated?
- Does the data analysis provide good summary context?
- Are the methods clearly defined and explained?
- Are the data and methods well-designed to answer the question? Any gaps?
- Are the results clearly presented?
- What would be a good extension for the analysis?
- What would be a good extension for the presentation?
- How is the structure of the paper? Any advice for structuring it?

You can use [the requirements for the final project](https://github.com/CPLN-680-Spring-2022/Class-Resources/blob/main/resources/final_project.pdf) as additional guidance.


**04-01 Code Review**: Code/implementation review of one peer project. We will discuss this in class.

**04-29 Final Project**: See the [project requirements]((https://github.com/CPLN-680-Spring-2022/Class-Resources/blob/main/resources/final_project.pdf).
 